### PR TITLE
Bumping libc for aarch64 support

### PR DESCRIPTION
**Pull request by chadbrewbaker**
Bumping libc for aarch64 support, removing compile warnings, bumping to 1.33.0 toolchain needed for libc

### CODE REVIEW

**Comment by ruuda** [comment]
Thank you for taking the time to open a pull request. Do you have any details about why libc 2.86 is needed for aarch64 support?

Could you please avoid introducing unnecessary formatting changes? Such changes make it harder to find the actual functional changes in the diff among the noise. Also, could you please follow [this commit message format](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)? In particular, the subject line should be short and imperative.

**Comment by chadbrewbaker** [comment]
Sorry, I ran rustfmt on the files I touched out of habit. I'm getting linker errors on the older libc crates for my M1 box on several projects.

**Comment by ruuda** [comment]
I pushed an alternative to master that bumps libc without reformatting code, and removes some outdated things from `Cago.toml`. Can you confirm that it works? If it does, I’ll make a new release.

**Comment by ruuda** [comment]
I’m going to assume the bump resolved this.

**Pull request closed without merging**
